site_name: Randominipedia
site_url: https://mydomain.org/randominipedia
site_description: A wiki for random things
site_author: Your Name
repo_url: https://github.com/KevinNokham/randominipedia
repo_name: GitHub
edit_uri: edit/main/docs/

theme:
  name: material
  palette: 
    scheme: slate
    primary: indigo
    accent: red
  
  features:
    - navigation.sections
nav:
  - Home: index.md
  - How To Contribute: howToGit.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences