site_name: Randominipedia
site_url: https://mydomain.org/mysite
theme:
  name: material

nav:
  - Home: index.md
  - How To Contribute: howToGit.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences